    spring:
        datasource:
          url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_0928c407282f0b9?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
          username: b7bcef9d79dc82
          password: 171156d6
        jpa:
          show-sql: true
          hibernate:
            ddl-auto: update
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
              connection:
                characterEncoding: utf-8
                CharSet: utf-8
                useUnicode: true
        jackson:
          serialization:
            INDENT_OUTPUT: true
        http:
            encoding:
              charset: UTF-8
              enabled: true
              force: true